### ISSUE TITLE
Capítulo 4

### ISSUE THREAD

**Issue by FabianoPrazeres** [livrowebservices/1ed#4]
Na classe CarroTest no código da página 79, não esta executando, esta aparecendo uma exceção na linha da busca no banco de dados para confirmar se o carro foi salvo, alguém sabe o que pode ser?

**Comment by diogensd** [comment]
Olá, Cole aqui o erro pra gente ver!

**Comment by FabianoPrazeres** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/14300386/15687620/19b392ae-274c-11e6-8284-14283173089a.png)

**Comment by diogensd** [comment]
O erro está que o objeto passado está chegando nulo, o erro esta na linha 45 mas na imagem não da pra ver. faz um staktrance() para verificar melhor

**Comment by FabianoPrazeres** [comment]
Encontrei o erro, ela estava na classe CarroDAO, porém agora surgiu um novo erro ao compilar.  

junit.framework.ComparisonFailure: expected:<Teste[ UPDATE]> but was:<Teste[]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)
	at test.CarroTest.testSalvarDeletarCarro(CarroTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:131)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by diogensd** [comment]
O teste de comparação "equals" falhou, verifique os dados que está testando pra ver se são idênticos.

**Comment by FabianoPrazeres** [comment]
Eles não estão idênticos
![sem titulo](https://cloud.githubusercontent.com/assets/14300386/15689525/ba95f47e-2755-11e6-861c-a95ea893ffa6.png)

**Comment by leonardocintra-luizalabs** [comment]
@FabianoPrazeres da uma olhada no meu codigo que eu fiz
https://github.com/leonardocintra/API-Carros/blob/master/API-Maven/Carros/src/test/java/test/CarroTest.java

Voce consegue debugar ?

**Comment by diogensd** [comment]
Fabiano:
Na sua imagem o erro descreve:
	-> esperado Teste[UPDATE] mas foi:
	-> Teste na linha 63

então executa o metodo savar e confere o que foi salvo no bd,
pois quando esá buscando pelo id esta retornando diferente.

pode ser um erro no seu metodo save ou update

**Comment by FabianoPrazeres** [comment]
Obrigado meu nobres colegas, problema solucionado, Obrigada pela ajuda de todos! Forte Abraço! Fiquem com Deus!!

**Comment by Vanderlucio** [comment]
Boa noite a todos não estou encontrando a falha ao executar o teste testSalvarDeletarCarro  alguém pode me ajudar por favor
![image](https://user-images.githubusercontent.com/52865182/61175279-c6bb3580-a582-11e9-8a59-bfda26f7650f.png)

**Comment by Vanderlucio** [comment]
acontece a atualização e também e salvo o conteúdo mais o método deletar não esta funcionando
